name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ankane/setup-mongodb@v1
        with:
          mongodb-version: 7.0
      - uses: ankane/setup-sqlserver@v1
        with:
          accept-eula: true
          sqlserver-version: 2019
      - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE testdb'
      - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -d testdb -Q 'SELECT @@VERSION'
      - uses: ankane/setup-mongodb@v1
        with:
          mongodb-version: 7.0
